
# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY . /app
RUN pip install --upgrade pip 
RUN pip install -r requirements.txt

EXPOSE 8081

CMD ["python", "app.py"]
